# Generated by Django 5.2.7 on 2025-10-16 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assetsManagementc', '0002_assetassignment_assetlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetassignment',
            options={'ordering': ['-assigned_date']},
        ),
        migrations.AlterModelTable(
            name='assetassignment',
            table='asset_assignment',
        ),
    ]
