# Generated by Django 5.2.7 on 2025-10-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsManagementc', '0003_alter_assetassignment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_amc',
            field=models.BooleanField(default=False),
        ),
    ]
