# Generated by Django 5.2.7 on 2025-10-22 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsManagementc', '0004_asset_is_amc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='asset_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='assetsManagementc.asset')),
            ],
            options={
                'db_table': 'asset_image',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
