# Generated by Django 5.2.7 on 2025-10-22 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsManagementc', '0005_assetimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='serial_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
