"""
Django settings for Backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import configparser
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

CONFIG_FILE_PATH = os.path.join(BASE_DIR,'../../itconfig.ini')
config = configparser.ConfigParser()
config.read(CONFIG_FILE_PATH)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w!&i+r(ljayt&y=i*alnjh7223mqws7&9mhiw&qj9ijdjpi-nc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config.getboolean('ITAssets', 'DEBUG')
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'employeeManagement',
    'assetsManagementc',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
    'corsheaders',
    'logs',
    'channels',
]

AUTH_USER_MODEL = 'employeeManagement.Employee'

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "logs.context.RequestContextMiddleware",  # if you create it; else remove this line
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Allow frontend to call backend
CORS_ALLOW_ALL_ORIGINS = True   # temporary for dev
# safer option:
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # React dev server
# ]

CORS_ALLOWED_ORIGINS = [
    "http://10.235.55.52", # if React is served directly
    "http://10.235.55.52:6770", # React dev server (optional)
    "http://localhost:6770",
    "http://127.0.0.1:6770",
]

ROOT_URLCONF = 'Backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI_APPLICATION = 'Backend.wsgi.application'

ASGI_APPLICATION = 'Backend.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_NAME = config.get('ITAssetsDB', 'DB_NAME')
DB_USER = config.get('ITAssetsDB', 'DB_USER')
DB_PSWD = config.get('ITAssetsDB', 'DB_PSWD')
DB_HOST = config.get('ITAssetsDB', 'DB_HOST')

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': DB_NAME,
        # 'USER': DB_USER,
        # 'PASSWORD': DB_PSWD,
        'HOST': DB_HOST,  # or your SQL Server host
        'PORT': '',           # default port is 1433
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'


USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST = config.get('ITAssetsMail', 'EMAIL_HOST')
EMAIL_PORT = config.getint('ITAssetsMail', 'EMAIL_PORT')
EMAIL_USE_TLS = config.getboolean('ITAssetsMail', 'EMAIL_USE_TLS')
EMAIL_HOST_USER = config.get('ITAssetsMail', 'EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config.get('ITAssetsMail', 'EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# JWT Authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=6),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'JWT authorization with **Bearer &lt;token&gt;**',
        }
    },
    'DEFAULT_INFO': 'Backend.urls.api_info',
    'USE_SESSION_AUTH': False,  # Disable Django login session in Swagger
    'SECURITY_REQUIREMENTS': [{'Bearer': []}],
}

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'formatters': {
#         'timestamped': {
#             'format': '[%(asctime)s] %(message)s',
#             'datefmt': '%d/%b/%Y %H:%M:%S',
#         },
#     },
#     'handlers': {
#         'db': {
#             'level': 'ERROR',
#             'class': 'logs.views.DatabaseLogHandler',
#         },
#         'console': {
#             'level': 'INFO',
#             'class': 'logging.StreamHandler',
#             'formatter': 'timestamped',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['db'],
#             'level': 'ERROR',
#             'propagate': True,
#         },
#         'custom': {
#             'handlers': ['db'],
#             'level': 'ERROR',
#             'propagate': False,
#         },
#         'django.server': {
#             'handlers': ['console'],
#             'level': 'INFO',
#             'propagate': False,
#         },
#     }
# }
