# Generated by Django 5.2.7 on 2025-10-04 08:46

import employeeManagement.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblEmployeeMaster',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('employee_id', employeeManagement.fields.VarCharCharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Employee_ID', max_length=8, primary_key=True, serialize=False)),
                ('id', models.IntegerField(db_column='ID', unique=True)),
                ('employee_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Employee_Name', max_length=200, null=True)),
                ('email_id', models.EmailField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email_ID', max_length=200, unique=True)),
                ('date_of_joining', models.DateField(blank=True, db_column='Date_Of_Joining', null=True)),
                ('is_active_raw', models.BigIntegerField(blank=True, db_column='Is_Active', null=True)),
                ('created_datedate', models.DateTimeField(blank=True, db_column='Created_Datedate', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_Date', null=True)),
                ('password', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PasswordHash', max_length=128, null=True)),
                ('is_staff', models.BooleanField(db_column='Is_Staff', default=False)),
                ('is_superuser', models.BooleanField(db_column='Is_Superuser', default=False)),
            ],
            options={
                'db_table': 'Tbl_Employee_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDepartmentMaster',
            fields=[
                ('id', models.IntegerField(db_column='ID', unique=True)),
                ('department_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Department_ID', max_length=8, primary_key=True, serialize=False)),
                ('department', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Department', max_length=200, null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_Date', null=True)),
            ],
            options={
                'db_table': 'Tbl_Department_Master',
                'managed': False,
            },
        ),
    ]
