# Generated by Django 5.2.7 on 2025-10-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblAssetCategory',
            fields=[
                ('id', models.IntegerField(db_column='ID', unique=True)),
                ('asset_category_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Asset_Category_ID', max_length=8, primary_key=True, serialize=False)),
                ('asset_category', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Asset_Category', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Tbl_Asset_Category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAssetMaster',
            fields=[
                ('id', models.IntegerField(db_column='ID', unique=True)),
                ('asset_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Asset_ID', max_length=8, primary_key=True, serialize=False)),
                ('asset_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Asset_Name', max_length=200, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='Created_date', null=True)),
            ],
            options={
                'db_table': 'Tbl_Asset_MAster',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAssetOwner',
            fields=[
                ('id', models.IntegerField(db_column='ID', unique=True)),
                ('asset_owner_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Asset_Owner_ID', max_length=8, primary_key=True, serialize=False)),
                ('assigned_to', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Assigned_To', max_length=200, null=True)),
                ('email_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email_Id', max_length=200, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='Created_Date', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_Date', null=True)),
            ],
            options={
                'db_table': 'Tbl_Asset_Owner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAssetPurchaseDetails',
            fields=[
                ('id', models.IntegerField(db_column='ID', unique=True)),
                ('asset_purchase_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Asset_Purchase_ID', max_length=8, primary_key=True, serialize=False)),
                ('pucase_order_no', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Pucase_Order_No', max_length=200, null=True)),
                ('purchase_value', models.FloatField(blank=True, db_column='Purchase_Value', null=True)),
                ('date_of_purchase', models.DateField(blank=True, db_column='Date_of_Purchase', null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='Created_Date', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_Date', null=True)),
            ],
            options={
                'db_table': 'Tbl_Asset_Purchase_Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAssetStatus',
            fields=[
                ('id', models.IntegerField(db_column='ID', unique=True)),
                ('asset_status_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Asset_Status_ID', max_length=9, primary_key=True, serialize=False)),
                ('asset_condition_good_fair_excellent', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Asset Condition. Good/Fair/Excellent', max_length=200, null=True)),
                ('in_amc', models.IntegerField(blank=True, db_column='In_AMC', null=True)),
                ('period_in_year_field', models.IntegerField(blank=True, db_column='Period(in_Year)', null=True)),
                ('warranty_description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Warranty_description', max_length=200, null=True)),
                ('amc_amount', models.IntegerField(blank=True, db_column='AMC_Amount', null=True)),
                ('warranty_start_date', models.DateField(blank=True, db_column='warranty Start Date', null=True)),
                ('warranty_over_date', models.DateField(blank=True, db_column='Warranty Over date', null=True)),
                ('remarks', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Remarks', max_length=200, null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='Created_Date', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_Date', null=True)),
            ],
            options={
                'db_table': 'Tbl_Asset_Status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAssetType',
            fields=[
                ('id', models.IntegerField(db_column='ID', unique=True)),
                ('asset_type_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Asset_Type_ID', max_length=8, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Asset_Type', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Tbl_Asset_Type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblAssignMaster',
            fields=[
                ('id', models.IntegerField(db_column='ID', unique=True)),
                ('assign_master_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Assign_Master_ID', max_length=8, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=200, null=True)),
                ('code', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Code', max_length=8, null=True)),
            ],
            options={
                'db_table': 'Tbl_Assign_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblLocationMaster',
            fields=[
                ('id', models.IntegerField(db_column='ID', unique=True)),
                ('location_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Location_ID', max_length=8, primary_key=True, serialize=False)),
                ('location', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Location', max_length=200, null=True)),
            ],
            options={
                'db_table': 'Tbl_Location_Master',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblServerAsset',
            fields=[
                ('id', models.IntegerField(db_column='ID', unique=True)),
                ('server_asset_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Server_Asset_ID', max_length=8, primary_key=True, serialize=False)),
                ('server_name_description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Server_Name_Description', max_length=200, null=True)),
                ('asset_model_no', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Asset_Model_No', max_length=200, null=True)),
                ('is_mission_critical', models.IntegerField(blank=True, db_column='Is_Mission_Critical', null=True)),
                ('asset_serial_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Asset_Serial_Number', max_length=200, null=True)),
                ('configuration', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Configuration', null=True)),
                ('operating_system', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Operating_System', max_length=200, null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_Date', null=True)),
            ],
            options={
                'db_table': 'Tbl_Server_Asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblSupplierMaster',
            fields=[
                ('id', models.IntegerField(db_column='ID', unique=True)),
                ('supplier_id', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Supplier_ID', max_length=8, primary_key=True, serialize=False)),
                ('supplier_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Supplier_Name', max_length=200, null=True)),
                ('email_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email_ID', max_length=200, null=True)),
                ('supplier_toll_free_or_support_field', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Supplier Toll Free or Support ', max_length=10, null=True)),
                ('is_active', models.BigIntegerField(blank=True, db_column='Is_Active', null=True)),
                ('created_datedate', models.DateTimeField(blank=True, db_column='Created_Datedate', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='Updated_Date', null=True)),
            ],
            options={
                'db_table': 'Tbl_Supplier_Master',
                'managed': False,
            },
        ),
    ]
