# Generated by Django 5.2.7 on 2025-10-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsManagementc', '0006_alter_asset_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('surrender_requested', 'Surrender Requested'), ('maintenance_requested', 'Maintenance Requested'), ('renew_requested', 'Renew Requested'), ('damaged_requested', 'Damaged Requested'), ('expired_requested', 'Expired Requested'), ('surrender_approved', 'Surrender Approved'), ('surrender_rejected', 'Surrender Rejected'), ('maintenance_approved', 'Maintenance Approved'), ('maintenance_rejected', 'Maintenance Rejected'), ('renew_approved', 'Renew Approved'), ('renew_rejected', 'Renew Rejected'), ('damaged_approved', 'Damaged Approved'), ('damaged_rejected', 'Damaged Rejected'), ('expired_approved', 'Expired Approved'), ('expired_rejected', 'Expired Rejected')], default='assigned', max_length=30),
        ),
    ]
