# Generated by Django 5.2.7 on 2025-10-29 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetsManagementc', '0007_assetassignment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('surrender_requested', 'Surrender Requested'), ('maintenance_requested', 'Maintenance Requested'), ('renew_requested', 'Renew Requested'), ('damaged_requested', 'Damaged Requested'), ('expired_requested', 'Expired Requested'), ('surrender_approved', 'Surrender Approved'), ('surrender_rejected', 'Surrender Rejected'), ('maintenance_approved', 'Maintenance Approved'), ('maintenance_rejected', 'Maintenance Rejected'), ('renew_approved', 'Renew Approved'), ('renew_rejected', 'Renew Rejected'), ('damaged_approved', 'Damaged Approved'), ('damaged_rejected', 'Damaged Rejected'), ('expired_approved', 'Expired Approved'), ('expired_rejected', 'Expired Rejected'), ('revoked', 'Revoked')], default='assigned', max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='assetsManagementc.asset')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='assetsManagementc.assetassignment')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
    ]
